#!/usr/bin/env python3
"""Generate dnsmasq configuration from the betting-domains.yaml pattern set.

Reads /etc/tmpmas/betting-domains.yaml and writes a dnsmasq snippet to
/etc/dnsmasq.d/blocked.conf. For each pattern in write_prohibited_patterns,
an `address=/<domain>/0.0.0.0` line is emitted.

Domains are extracted from the regex patterns. Only patterns with the shape
`(^|\\.)<domain>\\.<tld>$` are supported — anything else is skipped with a
warning. The betting-domains.yaml is maintained by DevOps and validated in CI.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

CONFIG_SOURCE = Path("/etc/tmpmas/betting-domains.yaml")
CONFIG_TARGET = Path("/etc/dnsmasq.d/blocked.conf")
UPSTREAM_DNS = ["1.1.1.1", "8.8.8.8"]

# Match the shape used in betting-domains.yaml:  (^|\.)bet365\.com$
PATTERN_RE = re.compile(r"^\(\^\|\\\.\)(.+?)\\\.(.+?)\$$")


def extract_domain(pattern: str) -> str | None:
    """Return the domain string from a supported pattern, else None."""
    match = PATTERN_RE.match(pattern)
    if not match:
        return None
    left, right = match.groups()
    # Left may itself contain escaped dots (e.g. "foo\.bar")
    left_clean = left.replace(r"\.", ".")
    right_clean = right.replace(r"\.", ".")
    return f"{left_clean}.{right_clean}"


def main() -> int:
    if not CONFIG_SOURCE.exists():
        print(f"ERROR: source not found: {CONFIG_SOURCE}", file=sys.stderr)
        return 1

    with CONFIG_SOURCE.open("r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    patterns = config.get("write_prohibited_patterns", [])
    domains: list[str] = []
    skipped: list[str] = []

    for entry in patterns:
        pattern = entry.get("pattern")
        if not pattern:
            continue
        domain = extract_domain(pattern)
        if domain is None:
            skipped.append(pattern)
            continue
        domains.append(domain)

    CONFIG_TARGET.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Auto-generated by ops/dns/generate-config.py — DO NOT EDIT",
        "# Source: /etc/tmpmas/betting-domains.yaml",
        "",
        "# Upstream resolvers for non-blocked queries",
        f"server={'server='.join(UPSTREAM_DNS)}".replace("server=", "", 1).rstrip("="),
    ]

    # Emit one line per upstream
    lines = [
        "# Auto-generated by ops/dns/generate-config.py — DO NOT EDIT",
        f"# Source: {CONFIG_SOURCE}",
        "",
    ]
    for upstream in UPSTREAM_DNS:
        lines.append(f"server={upstream}")

    lines.append("")
    lines.append("# Blocked domains — resolved to 0.0.0.0")
    for domain in domains:
        lines.append(f"address=/{domain}/0.0.0.0")

    lines.append("")
    lines.append("# Observability: log every query")
    lines.append("log-queries")
    lines.append("log-facility=-")

    CONFIG_TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Wrote {CONFIG_TARGET} with {len(domains)} blocked domains.")
    if skipped:
        print(f"Skipped {len(skipped)} patterns with unsupported shape:", file=sys.stderr)
        for p in skipped:
            print(f"  {p}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main())
